const champions = [
    {
        num: 1,
        name: "AATROX",
        image: "./images/aatrox.png",
        summoned: false,
    },
    {
        num: 2,
        name: "AHRI",
        image: "./images/ahri.png",
        summoned: false,
    },
    {
        num: 3,
        name: "ASHE",
        image: "./images/ashe.png",
        summoned: false,
    },
    {
        num: 4,
        name: "BRAND",
        image: "./images/brand.png",
        summoned: false,
    },
    {
        num: 5,
        name: "DIANA",
        image: "./images/diana.png",
        summoned: false,
    },
    {
        num: 6,
        name: "EZREAL",
        image: "./images/ezreal.png",
        summoned: false,
    },
    {
        num: 7,
        name: "FIORA",
        image: "./images/fiora.png",
        summoned: false,
    },
    {
        num: 8,
        name: "GALIO",
        image: "./images/galio.png",
        summoned: false,
    },
    {
        num: 9,
        name: "GAREN",
        image: "./images/garen.png",
        summoned: false,
    },
    {
        num: 10,
        name: "IRELIA",
        image: "./images/irelia.png",
        summoned: false,
    },
    {
        num: 11,
        name: "JAX",
        image: "./images/jax.png",
        summoned: false,
    },
    {
        num: 12,
        name: "JAYCE",
        image: "./images/jayce.png",
        summoned: false,
    },
    {
        num: 13,
        name: "KARTHUS",
        image: "./images/karthus.png",
        summoned: false,
    },
    {
        num: 14,
        name: "LEE SIN",
        image: "./images/leesin.png",
        summoned: false,
    },
    {
        num: 15,
        name: "LUX",
        image: "./images/lux.png",
        summoned: false,
    },
    {
        num: 16,
        name: "NOCTURNE",
        image: "./images/nocturne.png",
        summoned: false,
    },
    {
        num: 17,
        name: "OLAF",
        image: "./images/olaf.png",
        summoned: false,
    },
    {
        num: 18,
        name: "PANTHEON",
        image: "./images/pantheon.png",
        summoned: false,
    },
    {
        num: 19,
        name: "PYKE",
        image: "./images/pyke.png",
        summoned: false,
    },
    {
        num: 20,
        name: "QUINN",
        image: "./images/quinn.png",
        summoned: false,
    },
    {
        num: 21,
        name: "RIVEN",
        image: "./images/riven.png",
        summoned: false,
    },
    {
        num: 22,
        name: "SHEN",
        image: "./images/shen.png",
        summoned: false,
    },
    {
        num: 23,
        name: "SION",
        image: "./images/sion.png",
        summoned: false,
    },
    {
        num: 24,
        name: "SYLAS",
        image: "./images/sylas.png",
        summoned: false,
    },
    {
        num: 25,
        name: "SYNDRA",
        image: "./images/syndra.png",
        summoned: false,
    },
    {
        num: 26,
        name: "TALON",
        image: "./images/talon.png",
        summoned: false,
    },
    {
        num: 27,
        name: "TWISTED FATE",
        image: "./images/twistedfate.png",
        summoned: false,
    },
    {
        num: 28,
        name: "VAYNE",
        image: "./images/vayne.png",
        summoned: false,
    },
    {
        num: 29,
        name: "VI",
        image: "./images/vi.png",
        summoned: false,
    },
    {
        num: 30,
        name: "VIEGO",
        image: "./images/viego.png",
        summoned: false,
    },
    {
        num: 31,
        name: "VIKTOR",
        image: "./images/viktor.png",
        summoned: false,
    },
    {
        num: 32,
        name: "YASUO",
        image: "./images/yasuo.png",
        summoned: false,
    },
    {
        num: 33,
        name: "ZED",
        image: "./images/zed.png",
        summoned: false,
    },
    {
        num: 34,
        name: "ZILEAN",
        image: "./images/zilean.png",
        summoned: false,
    }
]

export default champions