export default [
    {
        num: 1,
        name: "Aatrox",
        image: "/src/assets/champions/aatrox.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 2,
        name: "Ahri",
        image: "/src/assets/champions/ahri.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 3,
        name: "Ashe",
        image: "/src/assets/champions/ashe.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 4,
        name: "Brand",
        image: "/src/assets/champions/brand.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 5,
        name: "Diana",
        image: "/src/assets/champions/diana.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 6,
        name: "Ezreal",
        image: "/src/assets/champions/ezreal.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 7,
        name: "Fiora",
        image: "/src/assets/champions/fiora.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 8,
        name: "Galio",
        image: "/src/assets/champions/galio.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 9,
        name: "Garen",
        image: "/src/assets/champions/garen.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 10,
        name: "Irelia",
        image: "/src/assets/champions/irelia.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 11,
        name: "Jax",
        image: "/src/assets/champions/jax.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 12,
        name: "Jayce",
        image: "/src/assets/champions/jayce.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 13,
        name: "Karthus",
        image: "/src/assets/champions/karthus.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 14,
        name: "Lee Sin",
        image: "/src/assets/champions/leesin.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 15,
        name: "Lux",
        image: "/src/assets/champions/lux.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 16,
        name: "Nocturne",
        image: "/src/assets/champions/nocturne.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 17,
        name: "Olaf",
        image: "/src/assets/champions/olaf.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 18,
        name: "Pantheon",
        image: "/src/assets/champions/pantheon.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 19,
        name: "Pyke",
        image: "/src/assets/champions/pyke.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 20,
        name: "Quinn",
        image: "/src/assets/champions/quinn.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 21,
        name: "Riven",
        image: "/src/assets/champions/riven.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 22,
        name: "Shen",
        image: "/src/assets/champions/shen.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 23,
        name: "Sion",
        image: "/src/assets/champions/sion.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 24,
        name: "Sylas",
        image: "/src/assets/champions/sylas.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 25,
        name: "Syndra",
        image: "/src/assets/champions/syndra.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 26,
        name: "Talon",
        image: "/src/assets/champions/talon.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 27,
        name: "Twisted Fate",
        image: "/src/assets/champions/twistedfate.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 28,
        name: "Vayne",
        image: "/src/assets/champions/vayne.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 29,
        name: "Vi",
        image: "/src/assets/champions/vi.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 30,
        name: "Viego",
        image: "/src/assets/champions/viego.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 31,
        name: "Viktor",
        image: "/src/assets/champions/viktor.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 32,
        name: "Yasuo",
        image: "/src/assets/champions/yasuo.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 33,
        name: "Zed",
        image: "/src/assets/champions/zed.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    },
    {
        num: 34,
        name: "Zilean",
        image: "/src/assets/champions/zilean.jpeg",
        summoned: false,
        isDisplayed: false,
        isSelected: false,
    }
]